routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'User\HomeController@index')->name('home');
Route::get('/home/{id}', 'User\HomeController@show')->name('home.show');

Auth::routes();

Route::get('/admin/dashboard', 'Admin\DashboardController@index')->name('dashboard');
Route::prefix('admin')->middleware('auth')->namespace('Admin')->group(function () {
    Route::resources([
        'users' => 'UserController',
        'category' => 'CategoryController',
        'book' => 'BookController',
    ]);
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'book_type',
        'book_number',
        'title',
        'description',
        'author',
        'publish_date',
        'pdf_file',
        'thumbnail',
        'created_by'
    ];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Support\Facades\Auth;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::orderBy('id', 'desc')->paginate(10);
        return view('admin.book.index', compact('books', $books));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.book.create', compact('categories', $categories));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'book_number' => 'required',
            'title' => 'required',
            'description' => 'required',
            'author' => 'required',
            'publish_date' => 'required',
            // 'pdf_file' => 'required',
            // 'thumbnail' => 'required',
        ]);

        $pdf_file = $request->file('pdf_file')->store('pdf_files');
        $thumbnail = $request->file('thumbnail')->store('thumbnails');

        // $book = new Book;
        // $book->book_type = 'elibrary';
        // $book->book_number = $request->book_number;
        // $book->title = $request->title;
        // $book->description = $request->description;
        // $book->author = $request->author;
        // $book->publish_date = $request->publish_date;
        // $book->pdf_file = $pdf_file;
        // $book->thumbnail = $thumbnail;
        // $book->created_by = Auth::id();
        // $book->save();

        $book = Book::create([
            'book_type' => 'elibrary',
            'book_number' => $request->book_number,
            'title' => $request->title,
            'description' => $request->description,
            'author' => $request->author,
            'publish_date' => $request->publish_date,
            'pdf_file' => $pdf_file,
            'thumbnail' => $thumbnail,
            'created_by' => Auth::id(),
        ]);

        $categories = Category::find($request->category);
        // dd($categories);

        $book->categories()->attach($categories);

        return redirect()->route('book.index')->with('success', 'Berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        $book->delete();

        return back();
    }
}

resources/views/admin/book/create.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Form</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('book.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">
                    
                            <div class="form-group row">
                                <label for="book_number" class="col-sm-3 col-form-label">Nomor Buku</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control @error('book_number') is-invalid @enderror" id="book_number" name="book_number" value="{{ old('book_number') }}">
                                    @error('book_number')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="title" class="col-sm-3 col-form-label">Judul</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title') }}">
                                    @error('title')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-sm-3 col-form-label">Deskripsi</label>
                                <div class="col-sm-9">
                                    <textarea class="summernote-simple @error('description') is-invalid @enderror" name="description">{{ old('description') }}</textarea>
                                    @error('description')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="author" class="col-sm-3 col-form-label">Pengarang</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control @error('author') is-invalid @enderror" id="author" name="author" value="{{ old('author') }}">
                                    @error('author')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="publish_date" class="col-sm-3 col-form-label">Tanggal Terbit</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control datepicker @error('publish_date') is-invalid @enderror" name="publish_date" value="{{ old('publish_date') }}">
                                    @error('publish_date')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="publish_date" class="col-sm-3 col-form-label">Kategori</label>
                                <div class="col-sm-9">
                                    <div class="selectgroup selectgroup-pills">
                                        @foreach ($categories as $category)
                                            <label class="selectgroup-item">
                                                <input type="checkbox" name="category[]" value="{{ $category }}" class="selectgroup-input">
                                                <span class="selectgroup-button">{{ $category->name }}</span>
                                            </label>
                                        @endforeach
                                        
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="pdf_file" class="col-sm-3 col-form-label">File Ebook</label>
                                <div class="col-sm-9">
                                    <input type="file" class="form-control @error('pdf_file') is-invalid @enderror" id="pdf_file" name="pdf_file" value="{{ old('pdf_file') }}" accept=".pdf">
                                    @error('pdf_file')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="thumbnail" class="col-sm-3 col-form-label">Cover</label>
                                <div class="col-sm-9">
                                    <input type="file" class="form-control @error('thumbnail') is-invalid @enderror" id="thumbnail" name="thumbnail" value="{{ old('thumbnail') }}" accept=".jpg,.png">
                                    @error('thumbnail')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                    
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('users.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('styles')
<link rel="stylesheet" href="{{ asset('stisla/node_modules/summernote/dist/summernote-bs4.css') }}">
<link rel="stylesheet" href="{{ asset('stisla/node_modules/bootstrap-daterangepicker/daterangepicker.css') }}">
@endpush

@push('scripts')
<script src="{{ asset('stisla/node_modules/summernote/dist/summernote-bs4.js') }}"></script>
<script src="{{ asset('stisla/node_modules/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
@endpush

resources/views/admin/book/edit.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Form</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('category.update', $category) }}" method="post">
                        @csrf
                        @method("PUT")
                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">
                    
                            <div class="form-group row">
                                <label for="name" class="col-sm-3 col-form-label">Nama Kategori</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ $category->name ?? old('name') }}">
                                    @error('name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                    
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('category.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/book/index.blade.php
@extends('admin.templates.default')

@section('content')

    <section class="section">
        <div class="section-header">
            <h1>Buku</h1>
        </div>
        
        @include('admin.templates.partials._alerts')

        <div class="section-body">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Daftar Buku</h4>
                        </div>
                        <div class="card-body p-0">
                            <div class="col-sm-12">
                                <a href="{{ route('book.create') }}" class="btn btn-primary btn-icon icon-left"><i class="fas fa-plus"></i> Tambah</a>
                            </div>
                        </div>
                        <div class="card-body p-1">
                            <div class="table-responsive">
                                <table class="table table-striped table-md">
                                    <tr>
                                        <th>#</th>
                                        <th>Nomor Buku</th>
                                        <th>Judul</th>
                                        <th>Pengarang</th>
                                        <th>Tanggal Terbit</th>
                                        <th>Cover</th>
                                        <th>Action</th>
                                    </tr>
                                    @foreach ($books as $key => $book)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $book->book_number }}</td>
                                        <td>{{ $book->title }}</td>
                                        <td>{{ $book->author }}</td>
                                        <td>{{ $book->publish_date }}</td>
                                        <td><img src="{{ asset('storage/'.$book->thumbnail) }}" height="100"></td>
                                        <td>
                                            <form action="{{ route('book.destroy', $book) }}" method="post">
                                                @csrf
                                                @method("DELETE")
                                                
                                                <a href="{{ route('book.edit', $book) }}" class="btn btn-info btn-icon icon-left"><i class="fas fa-edit"></i> Ubah</a>
                                                <button type="submit" class="btn btn-danger btn-icon icon-left"><i class="fas fa-trash"></i> Hapus</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            <nav class="d-inline-block">
                                {{ $books->links() }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </section>
@endsection